import * as fs from 'fs';
import * as path from 'path';

const BACKEND_TYPES_PATH = path.join(__dirname, '../src/types/index.ts');
const FRONTEND_TYPES_PATH = path.join(
  __dirname,
  '../../frontend/app/types/api.ts'
);

function syncTypes() {
  try {
    // Read the backend types file
    const backendTypes = fs.readFileSync(BACKEND_TYPES_PATH, 'utf-8');

    // Create frontend-compatible types
    const frontendTypes = `// AUTO-GENERATED FILE - DO NOT EDIT
// This file is automatically generated from backend types
// Last sync: ${new Date().toISOString()}

${backendTypes}
`;

    // Ensure frontend types directory exists
    const frontendTypesDir = path.dirname(FRONTEND_TYPES_PATH);
    if (!fs.existsSync(frontendTypesDir)) {
      fs.mkdirSync(frontendTypesDir, { recursive: true });
    }

    // Write to frontend
    fs.writeFileSync(FRONTEND_TYPES_PATH, frontendTypes, 'utf-8');

    console.log('✅ Types synced successfully!');
    console.log(`📁 From: ${BACKEND_TYPES_PATH}`);
    console.log(`📁 To: ${FRONTEND_TYPES_PATH}`);
  } catch (error) {
    console.error('❌ Error syncing types:', error);
    process.exit(1);
  }
}

syncTypes();
